version: '2'

services:

  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 3306:3306

  nginx:
    build: .
    ports:
      - 8000:80
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    command:  /bin/bash -c "/var/tmp/wait-for-it.sh backend:8888 -- nginx -g 'daemon off;'"

  backend:
    build: ./backend
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - "db"
    command: /bin/bash -c "./wait-for-it.sh db:3306 -- ./start.sh"

  frontend:
    build: ./frontend
