version: '2'

services:

  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 3306:3306

  nginx:
    image: nginx
#    ports:
#      - 80:80
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    network_mode: host
